# Generated by Django 5.0.6 on 2024-05-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_Carrera",
                    models.CharField(
                        max_length=50, verbose_name="Nombre de la carrera"
                    ),
                ),
                (
                    "titulo_Carrera",
                    models.CharField(
                        max_length=50, verbose_name="titulo de la carrera"
                    ),
                ),
                (
                    "anios_Estudio",
                    models.IntegerField(verbose_name="Anios de la carrera"),
                ),
                (
                    "numero_Horas",
                    models.IntegerField(verbose_name="Horas de la carrera"),
                ),
            ],
        ),
    ]
