# Generated by Django 5.0.6 on 2024-06-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Asignatura"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripcion de la Asignatura"),
                ),
                (
                    "numeroHoras_Docencia",
                    models.IntegerField(verbose_name="Numero Horas de Docencia"),
                ),
                (
                    "numeroHoras_Practica",
                    models.IntegerField(verbose_name="Numero de horas de Practica"),
                ),
                (
                    "numeroHoras_Autonomo",
                    models.IntegerField(verbose_name="Numero de horas Autonomo"),
                ),
                ("creditos", models.IntegerField(verbose_name="Creditos")),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("presencial", "Presencial"),
                            ("Virtual", "Virtual"),
                            ("hibrida", "hibrida"),
                        ],
                        max_length=20,
                        verbose_name="Modalidad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Malla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_malla",
                    models.CharField(max_length=100, verbose_name="Nombre de la malla"),
                ),
                (
                    "anioAprobacion",
                    models.IntegerField(verbose_name="Anio de la aprobacion"),
                ),
                (
                    "aniosVigencia",
                    models.IntegerField(verbose_name="Anio de vigencia de la Malla"),
                ),
                (
                    "estadovigente",
                    models.CharField(
                        choices=[
                            ("creado", "Creado"),
                            ("aprobado", "Aprobado"),
                            ("cancelado", "cancelado"),
                        ],
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Semestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreSemestre",
                    models.CharField(max_length=50, verbose_name="Nombre del Semestre"),
                ),
                (
                    "numeroSemestre",
                    models.IntegerField(verbose_name="Numero del semestre"),
                ),
            ],
        ),
    ]
