# Generated by Django 5.0.6 on 2024-06-03 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_asignatura_malla_semestre"),
    ]

    operations = [
        migrations.AddField(
            model_name="malla",
            name="carrera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.carrera",
                verbose_name="Selecciones una carerra",
            ),
        ),
        migrations.AddField(
            model_name="malla",
            name="semestres",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="core.semestre",
                verbose_name="Agrega los semestres",
            ),
        ),
    ]
