# Generated by Django 5.0.6 on 2024-06-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_persona_administrativo_docente_estudiante"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodoAcadémico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=30, verbose_name="Nombre del Periodo académico"
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(verbose_name="Fecha de inicio")),
                ("fecha_fin", models.DateTimeField(verbose_name="Fecha de Fin")),
                ("activo", models.BooleanField(default=True, verbose_name="Avtivo")),
            ],
        ),
    ]
