# Generated by Django 5.0.6 on 2024-06-05 15:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_periodoacadémico"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PeriodoAcadémico",
            new_name="PeriodoAcademico",
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=5, verbose_name="Ingresa el codigo"),
                ),
                (
                    "tipo_Pago",
                    models.CharField(
                        choices=[
                            ("directo", "Directo"),
                            ("transferencia", "Transferencia"),
                            ("crédito", "Credito"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Pago",
                    ),
                ),
                (
                    "comprobante_Pago",
                    models.ImageField(
                        upload_to="Comprobantes", verbose_name="Comprobante de Pago"
                    ),
                ),
                (
                    "fecha_Matricula",
                    models.DateField(
                        default=datetime.datetime, verbose_name="Fecha de Matricula"
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.carrera",
                        verbose_name="Carrera",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.estudiante",
                        verbose_name="Selecciones el estudiante",
                    ),
                ),
                (
                    "periodo_academico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.periodoacademico",
                        verbose_name="PeriodoAcademico",
                    ),
                ),
                (
                    "semestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.semestre",
                        verbose_name="Semestre",
                    ),
                ),
            ],
        ),
    ]
