# Generated by Django 5.0.6 on 2024-06-10 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_persona_edad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Ingrese el nombre del aula"
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(max_length=100, verbose_name="Ingrese el aula"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hora_entrada",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="Ingrese el horario formato [00:00 - 00:00 ]",
                    ),
                ),
                (
                    "hora_salida",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="Ingrese el horario formato [00:00 - 00:00 ]",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "horarioMateria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Horario",
                        to="core.horario",
                    ),
                ),
            ],
        ),
    ]
